# Generated by Django 4.2.5 on 2023-10-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poslugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('position', models.PositiveSmallIntegerField(unique=True)),
                ('description', models.TextField(max_length=800, unique=True)),
                ('span', models.CharField(max_length=100)),
            ],
        ),
    ]
